trigger:
  branches:
    include:
    - refs/heads/main
variables:
  - name: environment
    value: QA
  - group: companyQA
schedules:
- cron: 0 11 * * 1,2,3,4,5
  branches:
    include:
    - refs/heads/main
  always: true
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Linux-MSI-local
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: PowerShell@2
    displayName: PowerShell Script
    inputs:
      filePath: run.ps1
  - task: ArchiveFiles@2
    displayName: Archive output
    inputs:
      rootFolderOrFile: output
      archiveFile: $(Build.ArtifactStagingDirectory)/build-$(Build.BuildId).zip
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop-$(company)'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/build-$(Build.BuildId).zip
      ArtifactName: drop-$(company)
...